"""Tables and quoted numbers of the extended study (equal-budget benchmark, ablations, complexity).

    python make_q1_tables.py      # reads results/q1/<job>/results.json (and gaps.json), writes tables/q1_*.tex

Every number comes from the job outputs of methods/puformer/kaggle/jobs.py, copied to results/q1/ by
methods/puformer/kaggle/fetch_results.py. Missing jobs are printed as "--", so the paper builds at any time.
    tables/q1_bench_<dataset>.tex   methods x scales, PSNR / SSIM / SAM / ERGAS (self-ensemble off: single pass)
    tables/q1_full.tex              every metric of every benchmark job (supplementary)
    tables/q1_ablation.tex          PUFormer variants on Pavia Centre x4 (+ operator variants on CAVE x4)
    tables/q1_complexity.tex        parameters, FLOPs and T4 time of every method
    tables/q1_numbers.tex           values quoted in the text, as \\qone{key}
"""
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.environ.get("Q1_RESULTS", os.path.join(HERE, "..", "..", "results", "q1"))
OUT = os.path.join(HERE, "tables")

DATASETS = {"chikusei": ("Chikusei", (4, 8, 16)), "pavia": ("Pavia Centre", (4, 8, 16)),
            "cave": ("CAVE", (4, 8)), "harvard": ("Harvard", (4, 8))}
METHODS = [("bicubic", "Bicubic", None), ("gsa", "GSA", "aiazzi2007gsa"), ("ssrnet", "SSR-NET", "zhang2021ssrnet"),
           ("psrt", "PSRT", "deng2023psrt"), ("dct", "DCT", "ma2024reciprocal"),
           ("mimformer", "MIMFormer", "li2024mimformer"), ("dhif", "DHIF-Net", "huang2022dhif"),
           ("puformer", "PUFormer", None)]
BASELINES = ("ssrnet", "psrt", "dct", "mimformer", "dhif")      # the retrained published networks
# (key, label, decimals, higher is better)
SHORT = [("PSNR", "PSNR", 2, True), ("SSIM", "SSIM", 4, True), ("SAM", "SAM", 3, False), ("ERGAS", "ERGAS", 3, False)]
FULL = SHORT + [("CC", "CC", 4, True), ("SCC", "SCC", 4, True), ("Q2n", "Q2n", 4, True), ("RMSE_DN", "RMSE", 2, False)]
ABL = [("full", "PUFormer (full model)"), ("nophys", "no data step, no residual input"),
       ("nores", "no residual input"), ("zeros", "exact kernel, zero border"),
       ("learned", "learned blur kernel and SRF"), ("nomem", "no cross-stage memory"), ("k1", "$K=1$ stage"),
       ("k2", "$K=2$ stages"), ("k4", "$K=4$ stages"), ("conv", "convolutional mixer"),
       ("window", "$8\\times8$ window attention"), ("l1", "L1 + deep supervision only"),
       ("nodeep", "no deep supervision")]
# module settings of every variant, in the column order of the ablation table:
# data step, residual input, operator, memory, token mixer, stages K, SAM + SSIM loss, deep supervision
Y, N = "\\checkmark", "--"
FULL_MODULES = dict(step=Y, res=Y, op="exact", mem=Y, mixer="MDTA", K="3", loss=Y, deep=Y)
CHANGES = dict(full={}, nophys=dict(step=N, res=N), nores=dict(res=N), zeros=dict(op="zero border"),
               learned=dict(op="learned"), nomem=dict(mem=N), k1=dict(K="1", mem=N), k2=dict(K="2"), k4=dict(K="4"),
               conv=dict(mixer="conv"), window=dict(mixer="window"), l1=dict(loss=N), nodeep=dict(deep=N))
MODULE_COLS = [("step", "Data step"), ("res", "Res.\\ input"), ("op", "Operator $\\D,\\R$"), ("mem", "Memory"),
               ("mixer", "Mixer"), ("K", "$K$"), ("loss", "SAM+SSIM"), ("deep", "Deep sup.")]


def modules(v):
    """Module cells of variant v; the changed module is in bold."""
    m = dict(FULL_MODULES, **CHANGES[v])
    return [f"\\textbf{{{m[k]}}}" if k in CHANGES[v] else m[k] for k, _ in MODULE_COLS]
NUM = {}


def load(job, name="results.json"):
    p = os.path.join(RES, job, name)
    if not os.path.exists(p):
        return None
    with open(p) as f:
        return json.load(f)


def fmt(v, d):
    return "--" if v is None or (isinstance(v, float) and math.isnan(v)) else f"{v:.{d}f}"


def write(name, lines):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w", newline="\n") as f:
        f.write("% generated by make_q1_tables.py - do not edit\n" + "\n".join(lines) + "\n")


def method_metrics(ds, s, m):
    """Single-pass test metrics of method m on (ds, x s); bicubic and GSA come from the PUFormer job."""
    src = load(f"bench-{ds}-x{s}-puformer") if m in ("bicubic", "gsa") else load(f"bench-{ds}-x{s}-{m}")
    if src is None:
        return None
    if m == "bicubic":
        return src.get("bicubic_test")
    if m == "gsa":
        return src.get("gsa_test")
    return src["test"]


def best_marks(rows, cols):
    """Per column, the best value at printed precision among the learned methods' rows."""
    best = {}
    for k, _, d, hi in cols:
        vals = [round(r[k], d) for r in rows if r is not None and r.get(k) is not None]
        best[k] = (max if hi else min)(vals) if vals else None
    return best


def bench_table(ds):
    title, scales = DATASETS[ds]
    head = " & ".join(f"\\multicolumn{{{len(SHORT)}}}{{c}}{{$\\times${s}}}" for s in scales)
    rule = "".join(f"\\cmidrule(lr){{{2 + i * len(SHORT)}-{1 + (i + 1) * len(SHORT)}}}" for i in range(len(scales)))
    arrow = {True: "$\\uparrow$", False: "$\\downarrow$"}
    sub = " & ".join(" & ".join(lab + arrow[hi] for _, lab, _, hi in SHORT) for _ in scales)
    per = {s: {m: method_metrics(ds, s, m) for m, *_ in METHODS} for s in scales}
    best = {s: best_marks([per[s][m] for m, *_ in METHODS if m not in ("bicubic", "gsa")], SHORT) for s in scales}
    body = []
    for m, lab, cite in METHODS:
        name = lab + (f"~\\cite{{{cite}}}" if cite and m not in ("gsa",) else "")
        cells = []
        for s in scales:
            r = per[s][m]
            for k, _, d, hi in SHORT:
                v = None if r is None else r.get(k)
                c = fmt(v, d)
                if v is not None and m not in ("bicubic", "gsa") and round(v, d) == best[s][k]:
                    c = f"\\best{{{c}}}"
                cells.append(c)
        if m == "ssrnet":
            body.append("\\midrule")
        body.append(f"{name} & " + " & ".join(cells) + " \\\\")
    write(f"q1_bench_{ds}.tex", [
        "\\begin{table*}[t]", "\\centering",
        f"\\caption{{{title}: all methods retrained under the identical protocol and budget (4~h on one T4, "
        "same data, patches, batch, EMA and validation-only model selection; single pass). Best learned method in bold.}",
        f"\\label{{tab:q1-{ds}}}", "\\setlength{\\tabcolsep}{2.6pt}", "\\resizebox{\\textwidth}{!}{%",
        f"\\begin{{tabular}}{{@{{}}l{'c' * len(SHORT) * len(scales)}@{{}}}}", "\\toprule",
        f" & {head} \\\\", rule, f"Method & {sub} \\\\", "\\midrule", *body, "\\bottomrule", "\\end{tabular}}",
        "\\end{table*}"])
    for s in scales:
        for m, *_ in METHODS:
            if per[s][m]:
                NUM[f"{ds}{s}-{m}-psnr"] = f"{per[s][m]['PSNR']:.2f}"
                NUM[f"{ds}{s}-{m}-sam"] = f"{per[s][m]['SAM']:.3f}"
        it = {m: (load(f"bench-{ds}-x{s}-{m}") or {}).get("iters") for m, *_ in METHODS}
        for m, v in it.items():
            if v:
                NUM[f"{ds}{s}-{m}-iters"] = f"{v:,}".replace(",", "{,}")
        p, others = per[s]["puformer"], [per[s][m] for m in BASELINES if per[s][m]]
        if p and others:
            bo = max(others, key=lambda r: r["PSNR"])
            NUM[f"{ds}{s}-gain"] = f"{p['PSNR'] - bo['PSNR']:.2f}"
            NUM[f"{ds}{s}-psnr"] = f"{p['PSNR']:.2f}"
            NUM[f"{ds}{s}-sam"] = f"{p['SAM']:.3f}"
            NUM[f"{ds}{s}-rmse-red"] = f"{100 * (1 - p['RMSE_DN'] / bo['RMSE_DN']):.0f}"


def full_table():
    body = []
    for ds, (title, scales) in DATASETS.items():
        for s in scales:
            body.append(f"\\multicolumn{{{1 + len(FULL)}}}{{@{{}}l}}{{\\textit{{{title} $\\times${s}}}}} \\\\")
            for m, lab, _ in METHODS:
                r = method_metrics(ds, s, m)
                body.append(f"{lab} & " + " & ".join(fmt(None if r is None else r.get(k), d) for k, _, d, _ in FULL)
                            + " \\\\")
    write("q1_full.tex", [
        "\\begin{table*}[t]", "\\centering", "\\caption{All metrics of the equal-budget benchmark (single pass).}",
        "\\label{tab:q1-full}", "\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
        f"\\begin{{tabular}}{{@{{}}l{'c' * len(FULL)}@{{}}}}", "\\toprule",
        "Method & " + " & ".join(lab for _, lab, _, _ in FULL) + " \\\\", "\\midrule", *body, "\\bottomrule",
        "\\end{tabular}", "\\end{table*}"])


def _mean_std(vals):
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None
    mu = sum(vals) / len(vals)
    sd = math.sqrt(sum((v - mu) ** 2 for v in vals) / (len(vals) - 1)) if len(vals) > 1 else None
    return mu, sd


def abl_job(ds, v, seed=0):
    if v == "full" and seed == 0:
        return f"bench-{ds}-x4-puformer"
    return f"seed{seed}-{ds}-x4-{v}" if seed else f"abl-{ds}-x4-{v}"


def swap_psnr(g):
    """Worst swapped-operator PSNR over the three blur mismatches (None without a robustness run)."""
    if not g:
        return None
    vals = [g[k]["swap"]["PSNR"] for k in ("sigma=1.5", "sigma=2.5", "sigma=3.0") if k in g and "swap" in g[k]]
    return min(vals) if vals else None


def fixed_psnr(g):
    if not g:
        return None
    vals = [g[k]["fixed"]["PSNR"] for k in ("sigma=1.5", "sigma=2.5", "sigma=3.0") if k in g]
    return min(vals) if vals else None


def _psnr_of(r, seeds=()):
    """PSNR of a variant: the mean over its seeds when it has more than one, else its single run."""
    runs = [x for x in seeds if x]
    if len(runs) > 1:
        return _mean_std([x["test"]["PSNR"] for x in runs])[0]
    return None if r is None else r["test"]["PSNR"]


def _abl_row(idx, v, r, g, ref, seeds=()):
    """One row of the module-grid ablation table: index, module settings, then the metrics.
    `ref` is the reference PSNR (full model, seed mean when available); Delta compares like with like."""
    mods = " & ".join(modules(v))
    if r is None:
        return f"({idx}) & {mods} & " + " & ".join(["--"] * 7) + " \\\\"
    t, c = r["test"], r["consistency"]
    psnr = fmt(t["PSNR"], 2)
    if len([x for x in seeds if x]) > 1:
        mu, sd = _mean_std([x["test"]["PSNR"] for x in seeds if x])
        psnr = f"{mu:.2f}$\\pm${sd:.2f}"
    d = "--" if ref is None or v == "full" else f"{_psnr_of(r, seeds) - ref:+.2f}"
    return (f"({idx}) & {mods} & {r['params_M']:.2f} & {psnr} & {d} & {fmt(t['SAM'], 3)} & {fmt(t['ERGAS'], 3)} & "
            f"{fmt(c['cons_H_dB'], 1)}/{fmt(c['cons_M_dB'], 1)} & {fmt(swap_psnr(g), 2)} \\\\")


def _abl_numbers(prefix, v, r, g, ref, seeds=()):
    if r is None:
        return
    t, c = r["test"], r["consistency"]
    NUM[f"{prefix}-{v}-psnr"] = f"{t['PSNR']:.2f}"
    NUM[f"{prefix}-{v}-sam"] = f"{t['SAM']:.3f}"
    NUM[f"{prefix}-{v}-consH"] = f"{c['cons_H_dB']:.1f}"
    NUM[f"{prefix}-{v}-consM"] = f"{c['cons_M_dB']:.1f}"
    NUM[f"{prefix}-{v}-params"] = f"{r['params_M']:.2f}"
    if ref is not None and v != "full":
        dv = _psnr_of(r, seeds) - ref
        NUM[f"{prefix}-{v}-delta"] = f"{dv:+.2f}"
        NUM[f"{prefix}-{v}-absdelta"] = f"{abs(dv):.2f}"            # for prose ("costs 0.17 dB")
    if len([x for x in seeds if x]) > 1:
        mu, sd = _mean_std([x["test"]["PSNR"] for x in seeds if x])
        NUM[f"{prefix}-{v}-mean"], NUM[f"{prefix}-{v}-std"] = f"{mu:.2f}", f"{sd:.2f}"
        NUM[f"{prefix}-{v}-nseeds"] = str(len([x for x in seeds if x]))
    if swap_psnr(g) is not None:
        NUM[f"{prefix}-{v}-swap"] = f"{swap_psnr(g):.2f}"
        NUM[f"{prefix}-{v}-swaploss"] = f"{t['PSNR'] - swap_psnr(g):.2f}"
    if fixed_psnr(g) is not None:
        NUM[f"{prefix}-{v}-fixed"] = f"{fixed_psnr(g):.2f}"
        NUM[f"{prefix}-{v}-fixedloss"] = f"{t['PSNR'] - fixed_psnr(g):.2f}"


def ablation_table():
    """Module-grid ablation table: one row per variant, one column per module, then the metrics."""
    letters = "abcdefghijklmnopqrstuvwxyz"
    nmod = len(MODULE_COLS)
    head = "\\# & " + " & ".join(lab for _, lab in MODULE_COLS) + \
           " & Params (M) & PSNR & $\\Delta$ & SAM & ERGAS & Cons. (dB) & Swap \\\\"
    body, i = [], 0
    blocks = (("pavia", "abl", "Pavia Centre $\\times$4", [v for v, _ in ABL]),
              ("chikusei", "kabl", "Chikusei $\\times$4", ["full", "nophys", "zeros", "learned", "nomem", "k1", "conv"]),
              ("cave", "cabl", "CAVE $\\times$4", ["full", "nophys", "zeros", "learned"]))
    for b, (ds, prefix, title, variants) in enumerate(blocks):
        full_seeds = [load(abl_job(ds, "full", sd)) for sd in (0, 1, 2)] if ds == "pavia" else ()
        ref = _psnr_of(load(abl_job(ds, "full")), full_seeds)
        body.append(f"\\multicolumn{{{nmod + 8}}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\")
        for v in variants:
            r, g = load(abl_job(ds, v)), load(abl_job(ds, v), "gaps.json")
            seeds = [load(abl_job(ds, v, sd)) for sd in (0, 1, 2)] if ds == "pavia" and v in ("full", "zeros") else ()
            body.append(_abl_row(letters[i], v, r, g, ref, seeds))
            _abl_numbers(prefix, v, r, g, ref, seeds)
            NUM[f"{prefix}-{v}-row"] = letters[i]
            i += 1
            if v == "full":
                body.append("\\cmidrule(l){1-%d}" % (nmod + 8))
        if b < len(blocks) - 1:
            body.append("\\midrule")
    if "abl-full-mean" in NUM and "abl-zeros-mean" in NUM:
        NUM["abl-seed-gain"] = f"{float(NUM['abl-full-mean']) - float(NUM['abl-zeros-mean']):.2f}"
    write("q1_ablation.tex", [
        "\\begin{table*}[t]", "\\centering",
        "\\caption{Ablation study: each row changes one module of the full model (bold; \\checkmark: used, --: "
        "removed) and is trained from scratch with the same 4~h budget on one T4 (test set, single pass). "
        "$\\Delta$: PSNR change against row (a) of the same dataset. Cons.: $\\mathrm{PSNR}(\\D\\hat{\\X},\\YH)$/"
        "$\\mathrm{PSNR}(\\R\\hat{\\X},\\YM)$ in dB, with the simulation operators. Swap: worst test PSNR over blur "
        "$\\sigma\\in\\{1.5,2.5,3.0\\}$ when the true blur is given to the model at test time, for variants with an "
        "explicit operator. Rows with $\\pm$: mean and standard deviation over three seeds.}",
        "\\label{tab:ablation}", "\\setlength{\\tabcolsep}{3pt}", "\\resizebox{\\textwidth}{!}{%",
        f"\\begin{{tabular}}{{@{{}}c{'c' * nmod}|ccccccc@{{}}}}", "\\toprule", head, "\\midrule", *body,
        "\\bottomrule", "\\end{tabular}}", "\\end{table*}"])


def complexity_table():
    p = os.path.join(RES, "complexity.json")
    if not os.path.exists(p):
        write("q1_complexity.tex", ["% complexity.json not available yet"])
        return
    rows = json.load(open(p))
    sel = [r for r in rows if r.get("dataset") == "chikusei" and r.get("scale") == 4 and "error" not in r]
    name = {m: lab for m, lab, _ in METHODS}
    body = [f"{name[r['model']]} & {r['params_M']:.2f} & {r['gflops']:.0f} & {1000 * r['seconds']:.0f} & "
            f"{r['gpu_GB']:.2f} \\\\" for r in sel]
    write("q1_complexity.tex", [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Complexity for one $256\\times256$ Chikusei image (128 bands, $\\times$4) on one Tesla T4.}",
        "\\label{tab:complexity}", "\\begin{tabular}{@{}lcccc@{}}", "\\toprule",
        "Method & Params (M) & GFLOPs & Time (ms) & Memory (GB) \\\\", "\\midrule", *body, "\\bottomrule",
        "\\end{tabular}", "\\end{table}"])


def blind_table():
    """Blur estimated from the test pair (blind_eval.py): PSNR with the training, estimated and true operator."""
    body = []
    for ds, title in (("pavia", "Pavia Centre"), ("chikusei", "Chikusei")):
        b = load(f"blind-{ds}-x4", "blind.json")
        if not b:
            continue
        body.append(f"\\multicolumn{{7}}{{@{{}}l}}{{\\textit{{{title} $\\times$4}}}} \\\\")
        for key, r in b["blind"].items():
            noisy = ",snr=" in key
            lab = f"{r['sigma_true']:.1f}" + (" + noise" if noisy else "")
            cells = [fmt(r.get("sigma_abs_err"), 3), fmt(r.get("exact_fixed"), 2), fmt(r.get("exact_estimated"), 2),
                     fmt(r.get("exact_oracle"), 2), fmt(r.get("zeros_estimated"), 2), fmt(r.get("learned_fixed"), 2)]
            body.append(f"{lab} & " + " & ".join(cells) + " \\\\")
            tag = f"{ds}-s{r['sigma_true']:g}" + ("-noise" if noisy else "")
            for k in ("exact_fixed", "exact_estimated", "exact_oracle", "zeros_estimated", "learned_fixed"):
                if r.get(k) is not None:
                    NUM[f"blind-{tag}-{k}"] = f"{r[k]:.2f}"
            NUM[f"blind-{tag}-sigerr"] = f"{r['sigma_abs_err']:.3f}"
        for tag, rows in (("worst", [r for k, r in b["blind"].items() if ",snr=" not in k]),
                          ("noisy-worst", [r for k, r in b["blind"].items() if ",snr=" in k])):
            for k in ("exact_fixed", "exact_estimated", "zeros_estimated", "learned_fixed"):
                vals = [r[k] for r in rows if r.get(k) is not None]
                if vals:
                    NUM[f"blind-{ds}-{tag}-{k}"] = f"{min(vals):.2f}"
        errs = [r["sigma_abs_err"] for r in b["blind"].values()]
        NUM[f"blind-{ds}-max-sigerr"] = f"{max(errs):.3f}"
        NUM[f"blind-{ds}-grid"] = f"{b.get('grid_step', 0.05):.2f}"
        clean = b["blind"].get(f"sigma={b['nominal_sigma']:g}", {})
        noisy = b["blind"].get(f"sigma={b['nominal_sigma']:g},snr=35", {})
        for k in ("exact_fixed", "zeros_fixed", "learned_fixed"):
            if k in noisy:
                NUM[f"blind-{ds}-noisy-nominal-{k}"] = f"{noisy[k]:.2f}"
            if k in clean:
                NUM[f"blind-{ds}-nominal-{k}"] = f"{clean[k]:.2f}"
        for name, v in b.get("fixed_point_residual", {}).items():
            NUM[f"fp-{ds}-{name}-test"] = f"{100 * v['test']:.2f}"
            NUM[f"fp-{ds}-{name}-crop"] = f"{100 * v['crop64']:.2f}"
    if not body:
        write("q1_blind.tex", ["% blind.json not available yet"])
        return
    write("q1_blind.tex", [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Blur estimated from the test pair itself. $|\\Delta\\sigma|$: mean error of the estimated blur "
        "width; PSNR (dB) with the training operator (fixed), the estimated and the true blur given to the model, "
        "for the exact operator, the zero-border model (estimated) and the learned operator. Noise: 35~dB SNR on both "
        "inputs.}",
        "\\label{tab:blind}", "\\setlength{\\tabcolsep}{3pt}", "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tabular}{@{}lcccccc@{}}", "\\toprule",
        " & & \\multicolumn{3}{c}{Exact operator} & Zero border & Learned \\\\",
        "\\cmidrule(lr){3-5}",
        "Test blur $\\sigma$ & $|\\Delta\\sigma|$ & fixed & estimated & true & estimated & fixed \\\\", "\\midrule",
        *body,
        "\\bottomrule", "\\end{tabular}}", "\\end{table}"])


def long_numbers():
    for m in ("puformer", "mimformer"):
        r = load(f"long-pavia-x4-{m}")
        if r:
            NUM[f"long-{m}-psnr"] = f"{r['test']['PSNR']:.2f}"
            NUM[f"long-{m}-iters"] = f"{r['iters']:,}".replace(",", "{,}")
    a, b = load("long-pavia-x4-puformer"), load("long-pavia-x4-mimformer")
    if a and b:
        NUM["long-gap"] = f"{a['test']['PSNR'] - b['test']['PSNR']:.2f}"


def significance():
    """Paired Wilcoxon signed-rank test of per-image PSNR, PUFormer vs the best other method, per setting."""
    try:
        from scipy.stats import wilcoxon
    except ImportError:
        return
    wins = total = 0
    for ds, (_, scales) in DATASETS.items():
        for s in scales:
            p = load(f"bench-{ds}-x{s}-puformer")
            others = [(m, load(f"bench-{ds}-x{s}-{m}")) for m in BASELINES]
            others = [(m, r) for m, r in others if r]
            if not p or not others:
                continue
            m, b = max(others, key=lambda x: x[1]["test"]["PSNR"])
            a = [x["PSNR"] for x in p["test_per_image"]]
            c = [x["PSNR"] for x in b["test_per_image"]]
            total += 1
            wins += all(x > y for x, y in zip(a, c))
            pv = wilcoxon(a, c, alternative="greater").pvalue if len(a) >= 5 else float("nan")
            NUM[f"{ds}{s}-p"] = f"{pv:.1e}" if pv == pv else "--"
            NUM[f"{ds}{s}-best-other"] = dict((k, v) for k, v, _ in METHODS)[m]
            NUM[f"{ds}{s}-nimg"] = str(len(a))
            NUM[f"{ds}{s}-allwin"] = "all" if all(x > y for x, y in zip(a, c)) else \
                f"{sum(x > y for x, y in zip(a, c))} of {len(a)}"
    NUM["settings-allwin"], NUM["settings-total"] = str(wins), str(total)


def win_counts():
    """In how many finished settings PUFormer has the best PSNR / SAM / ERGAS among the retrained methods."""
    done = {"PSNR": 0, "SAM": 0, "ERGAS": 0}
    n = 0
    for ds, (_, scales) in DATASETS.items():
        for s in scales:
            p = method_metrics(ds, s, "puformer")
            others = [method_metrics(ds, s, m) for m in BASELINES]
            others = [o for o in others if o]
            if not p or not others:
                continue
            n += 1
            done["PSNR"] += p["PSNR"] > max(o["PSNR"] for o in others)
            done["SAM"] += p["SAM"] < min(o["SAM"] for o in others)
            done["ERGAS"] += p["ERGAS"] < min(o["ERGAS"] for o in others)
    NUM["settings-done"] = str(n)
    for k, v in done.items():
        NUM[f"wins-{k}"] = str(v)


def main():
    for ds in DATASETS:
        bench_table(ds)
    win_counts()
    full_table()
    ablation_table()
    complexity_table()
    blind_table()
    long_numbers()
    significance()
    write("q1_numbers.tex", [f"\\expandafter\\def\\csname qone@{k}\\endcsname{{{v}}}" for k, v in sorted(NUM.items())])
    print(f"{len(NUM)} numbers;", ", ".join(f"{k}={v}" for k, v in sorted(NUM.items())[:40]))


if __name__ == "__main__":
    main()
