"""Tables of the PUFormer paper that are generated from the result files (run from this folder).

    python make_tables.py        # writes tables/*.tex, which main.tex inputs

Every number in these tables is copied from results/ by code, not by hand:
    tables/pavia_compare.tex   Pavia Centre x4 against the 17 methods of TIP'26 Table IV
    tables/ours.tex            methods run under our pipeline, all PSNR / SSIM variants, both datasets
    tables/perimage.tex        per-image results of the final models, both datasets
    tables/robust.tex          blur / SRF mismatch with and without operator swap, and noise, both datasets
    tables/pavia_numbers.tex   values quoted in the text, as \\pav{key}
Set PAVIA_RESULTS to read the Pavia files from another folder.
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "..", "results")
CHI1 = os.path.join(RES, "puformer_chikusei_x4")
CHI3 = os.path.join(RES, "puformer_chikusei_x4_v3")
PAV = os.environ.get("PAVIA_RESULTS", os.path.join(RES, "puformer_pavia_x4"))
OUT = os.path.join(HERE, "tables")

CITE = {"GSA": "aiazzi2007gsa", "CNMF": "yokoya2012cnmf", "FUSE": "wei2015fuse", "U2Net": "peng2023u2net",
        "PSRT": "deng2023psrt", "DCT": "ma2024reciprocal", "DDIF": "cao2024ddif", "MIMFormer": "li2024mimformer",
        "MIMOSST": "fang2024mimosst", "OTPNet": "yu2025otpnet", "SMGU": "yan2025smgu", "AMSF": "liu2025amsf",
        "SSDT": "fu2025ssdt", "ASMNet": "liu2025asmnet", "DPFormer": "liu2026dpformer", "CLSNet": "yang2026clsnet",
        "Two-Stage Diffusion (TIP'26)": "chen2026twostage"}
LABEL = {"MIMOSST": "MIMO-SST", "Two-Stage Diffusion (TIP'26)": "Two-stage diffusion"}
# (TIP'26 column, our key, decimals, higher is better); our SSIM column uses the PSRT definition
COLS = [("PSNR", "PSNR", 4, True), ("SSIM", "SSIM_psrt", 4, True), ("SAM", "SAM", 4, False),
        ("ERGAS", "ERGAS", 4, False), ("Q2n", "Q2n", 4, True), ("CC", "CC", 4, True), ("SCC", "SCC", 4, True),
        ("RMSE_DN", "RMSE_DN", 2, False)]
ROBUST = [("Nominal", "nominal"), ("Blur $\\sigma=1.5$", "sigma=1.5"), ("Blur $\\sigma=2.5$", "sigma=2.5"),
          ("Blur $\\sigma=3.0$", "sigma=3.0"), ("SRF shift $-8$~nm", "srf_shift=-8nm"),
          ("SRF shift $+8$~nm", "srf_shift=+8nm"), ("Noise, 40~dB SNR", "noise_40dB"),
          ("Noise, 35~dB SNR", "noise_35dB"), ("Noise, 30~dB SNR", "noise_30dB")]


def load(*path):
    with open(os.path.join(*path)) as f:
        return json.load(f)


def fmt(v, d):
    return "--" if v is None else f"{v:.{d}f}"


def write(name, lines):
    with open(os.path.join(OUT, name), "w", newline="\n") as f:
        f.write("% generated by make_tables.py - do not edit\n" + "\n".join(lines) + "\n")


def tip_rows():
    with open(os.path.join(PAV, "tip26_table4_pavia.csv")) as f:
        return list(csv.DictReader(f))


def rank(ours, tip, d, hi):
    """1 + number of reported rows strictly better than ours at printed precision."""
    o = round(ours, d)
    return 1 + sum((round(t, d) > o) if hi else (round(t, d) < o) for t in tip)


def pavia_compare(res, tip):
    rows = [(f"{LABEL.get(r['method'], r['method'])}~\\cite{{{CITE[r['method']]}}}", [float(r[c]) for c, *_ in COLS])
            for r in tip]
    rows += [("PUFormer (single pass)", [res["test"][k] for _, k, *_ in COLS]),
             ("PUFormer (self-ensemble)", [res["test_tta"][k] for _, k, *_ in COLS])]
    best = [(max if hi else min)(round(r[1][j], d) for r in rows) for j, (_, _, d, hi) in enumerate(COLS)]
    body = []
    for i, (name, vals) in enumerate(rows):
        if i == len(tip):
            body.append("\\midrule")
        cells = [("\\best{%s}" if round(v, d) == best[j] else "%s") % fmt(v, d) for j, (v, (_, _, d, _)) in enumerate(zip(vals, COLS))]
        body.append(f"{name} & " + " & ".join(cells) + " \\\\")
    s, e = res["test"]["SSIM"], res["test_tta"]["SSIM"]
    write("pavia_compare.tex", [
        "\\begin{table*}[t]", "\\centering",
        "\\caption{Pavia Centre $\\times$4 comparison. All rows except PUFormer are reported in~\\cite{chen2026twostage} "
        "on the benchmark data released with PSRT~\\cite{deng2023psrt}; PUFormer is evaluated on our simulation of the "
        "same protocol from the original scene (Section~\\ref{sec:setup}). Best value per column in bold. SSIM of PUFormer "
        "uses the PSRT definition (data range 1); with data range equal to each image's maximum it is "
        f"{s:.4f} (single pass) and {e:.4f} (self-ensemble).}}",
        "\\label{tab:pavia}", "\\begin{tabular}{@{}lcccccccc@{}}", "\\toprule",
        "Method & PSNR$\\uparrow$ & SSIM$\\uparrow$ & SAM$\\downarrow$ & ERGAS$\\downarrow$ & Q2n$\\uparrow$ & "
        "CC$\\uparrow$ & SCC$\\uparrow$ & RMSE (DN)$\\downarrow$ \\\\", "\\midrule",
        *body, "\\bottomrule", "\\end{tabular}", "\\end{table*}"])


def ours_table(chi, chi_first, chi_gaps, ssrnet, pav):
    keys = [("PSNR", 2), ("PSNR_psrt", 2), ("MPSNR_peak1", 2), ("SSIM_psrt", 4), ("SSIM", 4), ("SAM", 3), ("RMSE_DN", 1)]
    row = lambda name, m: f"{name} & " + " & ".join(fmt(m.get(k), d) for k, d in keys) + " \\\\"
    write("ours.tex", [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Methods run under our pipeline, with all PSNR and SSIM definitions. P$_\\mathrm{g}$: peak = dataset "
        "maximum (headline); P$_\\mathrm{i}$: peak = image maximum; P$_\\mathrm{b}$: band-wise mean, peak 1. S$_1$: SSIM, "
        "data range 1; S$_\\mathrm{i}$: data range = image maximum.}",
        "\\label{tab:ours}", "\\setlength{\\tabcolsep}{3.2pt}", "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tabular}{@{}lccccccc@{}}", "\\toprule",
        "Method & P$_\\mathrm{g}$ & P$_\\mathrm{i}$ & P$_\\mathrm{b}$ & S$_1$ & S$_\\mathrm{i}$ & SAM & RMSE \\\\", "\\midrule",
        "\\multicolumn{8}{@{}l}{\\textit{Chikusei}} \\\\",
        row("Bicubic", chi["bicubic_test"]), row("GSA~\\cite{aiazzi2007gsa}", chi_gaps["nominal"]["gsa"]),
        row("SSR-NET~\\cite{zhang2021ssrnet}", ssrnet["test"]), row("PUFormer, first run", chi_first["test"]),
        row("PUFormer v3", chi["test"]), row("PUFormer v3, ensemble", chi["test_tta"]), "\\midrule",
        "\\multicolumn{8}{@{}l}{\\textit{Pavia Centre}} \\\\",
        row("Bicubic", pav["bicubic_test"]), row("GSA~\\cite{aiazzi2007gsa}", pav["gsa_test"]),
        row("PUFormer", pav["test"]), row("PUFormer, ensemble", pav["test_tta"]),
        "\\bottomrule", "\\end{tabular}}", "\\end{table}"])


def perimage_table(chi, pav):
    keys = [("PSNR", 2), ("SSIM", 4), ("SSIM_psrt", 4), ("SAM", 3), ("ERGAS", 3), ("Q2n", 4)]
    cells = lambda m: " & ".join(fmt(m.get(k), d) for k, d in keys)
    body = []
    for title, r in (("Chikusei, PUFormer v3", chi), ("Pavia Centre, PUFormer", pav)):
        body.append(f"\\multicolumn{{7}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\")
        body += [f"{i + 1} & {cells(m)} \\\\" for i, m in enumerate(r["test_per_image_tta"])]
        body += ["\\cmidrule(l){1-7}", f"Mean & {cells(r['test_tta'])} \\\\", "\\midrule"]
    write("perimage.tex", [
        "\\begin{table}[t]", "\\centering", "\\caption{Per-image results of the final models (self-ensemble)}",
        "\\label{tab:perimage}", "\\setlength{\\tabcolsep}{3.4pt}", "\\begin{tabular}{@{}ccccccc@{}}", "\\toprule",
        "Image & PSNR & S$_\\mathrm{i}$ & S$_1$ & SAM & ERGAS & Q2n \\\\", "\\midrule", *body[:-1],
        "\\bottomrule", "\\end{tabular}", "\\end{table}"])


def robust_table(chi_gaps, pav_gaps):
    def cells(g, key):
        r = g[key]
        pair = lambda m: f"{m['PSNR']:.2f} / {m['SAM']:.2f}"
        fixed, swap = r["fixed"], r.get("swap")
        win = None if key == "nominal" else ("swap" if swap and swap["PSNR"] > fixed["PSNR"] else "fixed")
        out = [pair(r["gsa"])]
        for name, m in (("fixed", fixed), ("swap", swap)):
            out.append("--" if m is None else (f"\\best{{{pair(m)}}}" if win == name else pair(m)))
        return out
    body = [f"{name} & " + " & ".join(cells(chi_gaps, key) + cells(pav_gaps, key)) + " \\\\" for name, key in ROBUST]
    write("robust.tex", [
        "\\begin{table*}[t]", "\\centering",
        "\\caption{Robustness of the final models (test PSNR in dB / SAM in degrees). Fixed: training operator; swap: true "
        "operator supplied at test time. The better PUFormer entry of each condition is in bold.}",
        "\\label{tab:robust}", "\\begin{tabular}{@{}lcccccc@{}}", "\\toprule",
        " & \\multicolumn{3}{c}{Chikusei (PUFormer v3)} & \\multicolumn{3}{c}{Pavia Centre (PUFormer)} \\\\",
        "\\cmidrule(lr){2-4}\\cmidrule(l){5-7}",
        "Condition & GSA & PUFormer fixed & PUFormer swap & GSA & PUFormer fixed & PUFormer swap \\\\", "\\midrule",
        *body, "\\bottomrule", "\\end{tabular}", "\\end{table*}"])


def pavia_numbers(res, hist, gaps, tip, q2n, sam):
    n = {}
    for tag, m in (("S", res["test"]), ("E", res["test_tta"])):
        for k, d in (("PSNR", 2), ("PSNR_psrt", 2), ("MPSNR_peak1", 2), ("SSIM", 4), ("SSIM_psrt", 4), ("SAM", 3),
                     ("ERGAS", 3), ("RMSE_DN", 1), ("CC", 4), ("SCC", 4), ("Q2n", 4)):
            n[f"{tag}-{k}"] = fmt(m[k], d)
    firsts = []
    for c, k, d, hi in COLS:
        vals = [float(r[c]) for r in tip]
        b = (max if hi else min)(range(len(tip)), key=lambda i: vals[i])
        r = rank(res["test_tta"][k], vals, d, hi)
        n[f"rank-{c}"], n[f"tipbest-{c}"] = str(r), fmt(vals[b], d)
        n[f"tipbestname-{c}"] = LABEL.get(tip[b]["method"], tip[b]["method"])
        firsts += [c] if r == 1 else []
    n["first"] = str(len(firsts))
    n["firstlist"] = ", ".join(firsts)
    t = {c: max(float(r[c]) for r in tip) if hi else min(float(r[c]) for r in tip) for c, _, _, hi in COLS}
    e = res["test_tta"]
    n["gain-PSNR"] = f"{e['PSNR'] - t['PSNR']:.2f}"
    for c, k in (("RMSE_DN", "RMSE_DN"), ("ERGAS", "ERGAS"), ("SAM", "SAM")):
        n[f"red-{c}"] = f"{100 * (1 - e[k] / t[c]):.1f}"
    n["cons-H"], n["cons-M"] = f"{res['consistency_tta']['cons_H_dB']:.1f}", f"{res['consistency_tta']['cons_M_dB']:.1f}"
    gsa_tip = next(r for r in tip if r["method"] == "GSA")
    n["gsa-PSNR"], n["gsa-SAM"], n["tipgsa-PSNR"] = f"{res['gsa_test']['PSNR']:.2f}", f"{res['gsa_test']['SAM']:.2f}", f"{float(gsa_tip['PSNR']):.2f}"
    n["gsa-gap"] = f"{float(gsa_tip['PSNR']) - res['gsa_test']['PSNR']:.2f}"
    n["bic-PSNR"] = f"{res['bicubic_test']['PSNR']:.2f}"
    best = max((h for h in hist if h["it"] > 0), key=lambda h: h["val_PSNR"])
    n["iters"], n["hours"], n["params"] = f"{res['iters']:,}".replace(",", "{,}"), f"{res['train_hours']:.1f}", f"{res['params_M']:.2f}"
    n["patches"] = f"{res['iters'] * 8 * res['gpus'] / 1e6:.2f}"
    n["best-it"], n["best-val"] = f"{best['it']:,}".replace(",", "{,}"), f"{res['best_val_PSNR']:.2f}"
    peak = max((h for h in hist if h["it"] > 0), key=lambda h: h["test_PSNR"])     # logged only, never used
    n["test-peak"], n["test-peak-it"] = f"{peak['test_PSNR']:.2f}", f"{peak['it']:,}".replace(",", "{,}")
    n["test-at-best"], n["test-end"] = f"{best['test_PSNR']:.2f}", f"{hist[-1]['test_PSNR']:.2f}"
    n["infer"] = f"{res['infer_s_per_256']:.2f}"
    per = [m["PSNR"] for m in res["test_per_image_tta"]]
    n["visual-tile"] = str(per.index(min(per)) + 1)          # hardest test image, shown in the visual figure
    nom = gaps["nominal"]["fixed"]["PSNR"]
    blur = [k for _, k in ROBUST if k.startswith("sigma")]
    n["blur-fixed-loss-min"] = f"{min(nom - gaps[k]['fixed']['PSNR'] for k in blur):.1f}"
    n["blur-fixed-loss-max"] = f"{max(nom - gaps[k]['fixed']['PSNR'] for k in blur):.1f}"
    n["blur-swap-loss-max"] = f"{max(nom - gaps[k]['swap']['PSNR'] for k in blur):.2f}"
    srf = [k for _, k in ROBUST if k.startswith("srf")]
    n["srf-swap-delta"] = f"{max(gaps[k]['fixed']['PSNR'] - gaps[k]['swap']['PSNR'] for k in srf):.1f}"
    for db in (40, 35, 30):
        g = gaps[f"noise_{db}dB"]
        n[f"noise{db}-margin"] = f"{g['fixed']['PSNR'] - g['gsa']['PSNR']:.1f}"
    if q2n:
        n["q2n"] = f"{q2n['Q2n']:.4f}"
        n["q2n-def10"] = f"{100 * q2n['deficit_share_worst']['0.1']:.0f}\\%"
        n["q2n-def50"] = f"{100 * q2n['deficit_share_worst']['0.5']:.0f}\\%"
        rel = q2n["relative_error_worst10pct_by_group_of_8_bands"]
        n["q2n-relmax"], n["q2n-relmin"] = f"{max(rel):.3f}", f"{min(rel):.3f}"
        c = q2n["q2n_vs_psnr_blend_to_bicubic"]
        n["calib-psnr-hi"], n["calib-q-hi"], n["calib-psnr-mid"], n["calib-q-mid"] = (
            f"{c[0]['PSNR']:.2f}", f"{c[0]['Q2n']:.4f}", f"{c[3]['PSNR']:.2f}", f"{c[3]['Q2n']:.4f}")
    if sam:
        w, fl = sam["water"], sam["noise_floor"]
        for i, share in enumerate(w["share_per_image"]):
            n[f"water-{i + 1}"] = f"{100 * share:.0f}"
        for k, tag in (("PUFormer", ""), ("GSA", "gsa-")):
            n[f"{tag}sam-water"], n[f"{tag}sam-nowater"] = f"{w[k]['water']:.2f}", f"{w[k]['other']:.2f}"
            n[f"{tag}sam-nowater-2"] = f"{w[k]['per_image_other'][1]:.2f}"
            n[f"{tag}sam-dark10"] = f"{100 * sam['darkest_share'][k]['0.1']:.0f}"
        n["noise-floor"] = f"{fl['mean_angle']:.2f}"
        n["noise-floor-2"] = f"{fl['per_image'][1]:.2f}"
        n["noise-floor-dark"] = f"{fl['by_brightness'][0]:.1f}"
        n["noise-floor-bright"] = f"{fl['by_brightness'][-1]:.2f}"
        n["zero-pixels"] = str(sum(sam["zero_pixels"]))
    lines = ["\\makeatletter"] + [f"\\@namedef{{pav@{k}}}{{{v}}}" for k, v in n.items()] + ["\\makeatother"]
    write("pavia_numbers.tex", lines)
    return n


def main():
    os.makedirs(OUT, exist_ok=True)
    chi, chi_first = load(CHI3, "puformer", "results.json"), load(CHI3, "first_run_reeval", "results.json")
    chi_gaps, ssrnet = load(CHI3, "puformer", "gaps.json"), load(CHI1, "ssrnet", "results.json")
    pav, pav_gaps, pav_hist = (load(PAV, "puformer", f) for f in ("results.json", "gaps.json", "history.json"))
    q = os.path.join(PAV, "paper_analysis", "q2n.json")
    s = os.path.join(PAV, "sam_analysis", "sam.json")
    tip = tip_rows()
    pavia_compare(pav, tip)
    ours_table(chi, chi_first, chi_gaps, ssrnet, pav)
    perimage_table(chi, pav)
    robust_table(chi_gaps, pav_gaps)
    n = pavia_numbers(pav, pav_hist, pav_gaps, tip, load(q) if os.path.exists(q) else None,
                      load(s) if os.path.exists(s) else None)
    print("tables:", sorted(os.listdir(OUT)))
    print({k: v for k, v in n.items() if k.startswith(("E-", "rank-", "first", "gain", "red", "gsa", "iters", "best"))})


if __name__ == "__main__":
    main()
