"""Write numbers.tex (LaTeX macros) from the paper analysis results, so the text quotes the files exactly.

    python make_numbers.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ANA = os.path.join(HERE, "..", "..", "results", "puformer_chikusei_x4_v3", "paper_analysis")

q = json.load(open(os.path.join(ANA, "q2n.json")))
rel = q["relative_error_worst10pct_by_group_of_8_bands"]
o = q["oracle_injection_rmse_dn"]["0"]
calib = q["q2n_vs_psnr_blend_to_bicubic"]
beats_oracle = all(v["model"] < v["oracle_linear"] for v in q["oracle_injection_rmse_dn"].values())
macros = {
    "QtwonVthree": f"{q['Q2n']:.4f}",
    "QtwonExactUV": f"{q['bands_0_7_exact']:.4f}",
    "QtwonExactUVNIR": f"{q['bands_0_7_104_127_exact']:.4f}",
    "RelErrUV": f"{rel[0]:.2f}",
    "RelErrMaxOther": f"{max(rel[1:]):.3f}",
    "OracleBicA": f"{o['bicubic']:.1f}",
    "OracleLinA": f"{o['oracle_linear']:.1f}",
    "OracleModelA": f"{o['model']:.1f}",
    "DefTen": f"{100 * q['deficit_share_worst']['0.1']:.0f}\\%",
    "DefFifty": f"{100 * q['deficit_share_worst']['0.5']:.0f}\\%",
    "CalibPsnrHi": f"{calib[0]['PSNR']:.2f}", "CalibQHi": f"{calib[0]['Q2n']:.4f}",
    "CalibPsnrMid": f"{calib[3]['PSNR']:.2f}", "CalibQMid": f"{calib[3]['Q2n']:.4f}",
}
with open(os.path.join(HERE, "numbers.tex"), "w") as f:
    f.write("% generated by make_numbers.py from results/puformer_chikusei_x4_v3/paper_analysis/q2n.json\n")
    for k, v in macros.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(macros, "model beats oracle in every checked band:", beats_oracle)
